const projects = [
    {
        areaSolve: 'Construcción',
        client: 'Ludwig Van Oosterzee',
        clientLogo: null,
        backgroundImg: 'https://images.pexels.com/photos/2089698/pexels-photo-2089698.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&dpr=1',
        houseType: 'Personalizado',
        reviewEs: `loremEs`,
        reviewEn: `lorem-En`,
        info: 'Proyecto de 4 habitaciones con estructura de MetalCon, Marbella',
    },
    {
        areaSolve: 'Construcción',
        client: 'Ruth Pilar',
        clientLogo: null,
        backgroundImg: '',
        houseType: '1',
        reviewEs: `loremEs`,
        reviewEn: `lorem-En`,
        info: '',
    },
    {
        areaSolve: 'Construcción',
        client: 'Gallardo',
        clientLogo: null,
        backgroundImg: '',
        houseType: '1',
        reviewEs: `loremEs`,
        reviewEn: `lorem-En`,
        info: '',
    },
    {
        areaSolve: 'Construcción',
        client: 'Silvia',
        clientLogo: null,
        backgroundImg: '',
        houseType: '1',
        reviewEs: `loremEs`,
        reviewEn: `lorem-En`,
        info: '',
    },
    {
        areaSolve: 'Construcción',
        client: 'Bellolio',
        clientLogo: null,
        backgroundImg: '',
        houseType: '1',
        reviewEs: `loremEs`,
        reviewEn: `lorem-En`,
        info: '',
    },
]

export { projects }